### ISSUE TITLE
[Imker] Exception "java.util.zip.ZipException: Not in GZIP format"

### ISSUE THREAD

**Issue by askeuhd** [MarcoFalke/wiki-java-tools#41]
I get this error no mattter what I try to download - worked fine a couple of days ago. 

The software can read file lists just fine, both ones I made myself or loading a category, but when actually attempts to download anything (of Commons) this error occurs: 

Version: v16.09.13
Stack trace:
```java
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at wiki.Wiki.fetch(Unknown Source)
	at wiki.Wiki.getImage(Unknown Source)
	at wiki.Wiki.getImage(Unknown Source)
	at app.ImkerBase$1.fetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.ImkerBase.downloadLoop(Unknown Source)
	at app.ImkerGUI$4.doInBackground(Unknown Source)
	at app.ImkerGUI$4.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by reinhix2** [comment]
+1
After succesful downloads earlier, I got same ZipException. Exactly same stack trace. Source selection both by page or by category.

**Comment by real68er** [comment]
+1

**Comment by Viejomartin** [comment]
I got the same Exception using Fedora 35. Does anyone know how to build the newest version on Linux?
