### ISSUE TITLE
[Imker] Exception

### ISSUE THREAD

**Issue by real68er** [MarcoFalke/wiki-java-tools#44]
Version: v16.09.13
Stack trace:
```java
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at wiki.Wiki.fetch(Unknown Source)
	at wiki.Wiki.getImage(Unknown Source)
	at wiki.Wiki.getImage(Unknown Source)
	at app.ImkerBase$1.fetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.App.attemptFetch(Unknown Source)
	at app.ImkerBase.downloadLoop(Unknown Source)
	at app.ImkerGUI$4.doInBackground(Unknown Source)
	at app.ImkerGUI$4.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by JoKalliauer** [comment]
VicuñaUploader had the same problem and solved it:
https://github.com/yarl/vicuna/pull/172

Further links: (thanks to @Nightflyer )
* https://commons.wikimedia.org/wiki/Commons:Forum/Archiv/2021/October#Anmeldeproblem
* https://commons.wikimedia.org/wiki/Commons:Forum/Archiv/2021/October#Problem_beim_Hochladen_mit_Commonist
* https://commons.wikimedia.org/wiki/Commons_talk:Commonist
* https://commons.wikimedia.org/wiki/Commons:Forum/Archiv/2021/December#Vicunja_Hilfe
* https://commons.wikimedia.org/wiki/Commons_talk:Imker_(batch_download)

**Comment by JoKalliauer** [comment]
Reported upstream: https://phabricator.wikimedia.org/T298340
